name: Cross-platform CI

on:
  push:
    paths:
      - '.github/workflows/ci.yaml'
      - 'src/*'
      - 'inc/*'
      - 'CMakeLists.txt'
      - '*.cmake'
  pull_request:
    paths:
      - '.github/workflows/ci.yaml'
      - 'src/*'
      - 'inc/*'
      - 'CMakeLists.txt'
      - '*.cmake'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 1
    - name: Test
      id: test
      shell: bash
      run: |
        cmake --build build --config Debug -j8
        ctest --build-config Release --output-on-failure --test-dir build/test
    - name: Setup LCOV
      if: ${{ matrix.os == 'ubuntu-20.04' }} # Only run coverage on Ubuntu 20.04
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: Generate code coverage report
      if: ${{ matrix.os == 'ubuntu-20.04' }} # Only run coverage on Ubuntu 20.04
      shell: bash
      run: |
        cmake --build build --config Debug -j8
        ctest --build-config Debug --test-dir build/test
        lcov --capture --directory build/test --exclude '/usr/*' --output-file lcov_coverage.info
        lcov --remove lcov_coverage.info "$(pwd)/inc/*" "$(pwd)/test/*" --output-file lcov_coverage.info
        lcov --list lcov_coverage.info
    - name: Build
      id: build
      shell: bash
      run: |
        cmake -B build
        cmake --build build --config Release --target install -j8
    - name: Package
      id: package
      shell: bash
      run: |
        cmake --build build --config Release --target package -j8
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ matrix.os == 'windows-2019' || failure() || github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
