name: Cross-platform CI

on:
  push:
    paths:
      - '.github/workflows/ci.yaml'
      - 'src/*'
      - 'inc/*'
      - 'CMakeLists.txt'
      - '*.cmake'
  pull_request:
    paths:
      - '.github/workflows/ci.yaml'
      - 'src/*'
      - 'inc/*'
      - 'CMakeLists.txt'
      - '*.cmake'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 0
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: Build and Test
      id: test
      shell: bash
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build --config Debug --target install -j8
        ctest --build-config Debug --test-dir build/test --output-on-failure
    - name: Generate code coverage report
      shell: bash
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build --config Debug --target coverage -j8
        lcov --list build/test/coverage.info
    - name: Package
      id: package
      shell: bash
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release --target package -j8
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() || github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
